### ISSUE TITLE
No need to include sketchtools binery

### ISSUE THREAD

**Issue by cognitom** [iDuuck/sketchjs#3]
I'm not sure about the license of `sketchtools` because there's no mention about it inside that tool and [the site](http://bohemiancoding.com/sketch/tool/). But it seems not MIT license, at least. So, my concern is that `sketchjs` can include it legally, or not.

How about downloading on "postinstall" hook? For example, this code will download and install `sketchtool` automatically:

``` sh
#!/usr/bin/env bash

mkdir sketchtool_installer
cd sketchtool_installer
curl -L -o temp.zip http://sketchtool.bohemiancoding.com/sketchtool-latest.zip
unzip temp.zip
cd sketchtool
sh ./install.sh
cd ../../
rm -Rf sketchtool_installer
```

**Comment by iduuck** [comment]
Used another installation script by `gulp-sketch`. Added an `./install.sh`, but the user needs to run this manually.
